### ISSUE TITLE
Use Simpler GitHub Pages publishing?

### ISSUE THREAD

**Issue by bwtakacy** [ossc-db/syncdb#1]
See the GitHub announce https://github.com/blog/2228-simpler-github-pages-publishing and the discussion in ossc-db/pg_rman#36.

How do you think, @kfuru ?

**Comment by kfuru** [comment]
I tried it in the same way as dblink_plus.
How about this?

**Comment by bwtakacy** [comment]
Excellent!

This makes us feeling easy to maintain a documentations :smile:
Thank you for everything about this.
