### ISSUE TITLE
"ERROR - refresh error, see server logs for details" and nothing in DB server log 

### ISSUE THREAD

**Issue by kotsachin** [ossc-db/syncdb#2]
Hi ,

I am testing syncdb tool to replicate a table from PostgreSQL to Oracle.

PostgreSQL version: 9.5.4
PostgreSQL driver: postgresql-9.4.1212.jre7.jar
Oracle version: 11.2.0.1.0
Oracle driver: ojdbc6.jar
Java version: 1.7.0_45

I have created one master  table in PostgreSQL  and replica table in Oracle with same definition.

I am getting below error:
```
$ syncdb attach --master postgres --server oracle --schema syncdb --table rep_accounts
input query : SELECT aid, bid, abalance FROM "public"."pgbench_accounts"
ERROR - refresh error, see server logs for details

**Comment by bwtakacy** [comment]
Hi! 😄 

Could you upload the server logs?

**Comment by kotsachin** [comment]
Hi,

Thanks for instant reply.

$ date
Wed Dec  7 15:56:35 IST 2016

$ syncdb attach --master postgres --server oracle --schema syncdb --table rep_accounts
input query : SELECT aid, bid, abalance FROM "public"."pgbench_accounts"
ERROR - refresh error, see server logs for details


PostgreSQL DB logs:
$ tail -10f /u01/pgsqldata/pg_log/postgresql-Wed.log 
```rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]
< 2016-12-07 13:00:14.072 IST >FATAL:  archive command failed with exit code 255
< 2016-12-07 13:00:14.072 IST >DETAIL:  The failed archive command was: rsync -a pg_xlog/000000030000000000000074 postgres@192.168.56.102:/u01/walarchives/000000030000000000000074
< 2016-12-07 13:00:14.073 IST >LOG:  archiver process (PID 5096) exited with exit code 1
ssh: connect to host 192.168.56.102 port 22: No route to host
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]
< 2016-12-07 13:00:33.992 IST >FATAL:  archive command failed with exit code 255
< 2016-12-07 13:00:33.992 IST >DETAIL:  The failed archive command was: rsync -a pg_xlog/000000030000000000000074 postgres@192.168.56.102:/u01/walarchives/000000030000000000000074
< 2016-12-07 13:00:33.994 IST >LOG:  archiver process (PID 5100) exited with exit code 1
```

PostgreSQL server logs:
\# tailf -10f /var/log/messages
```Dec  7 15:46:59 clone-2 NetworkManager[1391]: <info> (eth12): DHCPv4 state changed renew -> renew
Dec  7 15:46:59 clone-2 NetworkManager[1391]: <info>   address 192.168.56.101
Dec  7 15:46:59 clone-2 NetworkManager[1391]: <info>   prefix 24 (255.255.255.0)
Dec  7 15:46:59 clone-2 dhclient[4657]: bound to 192.168.56.101 -- renewal in 548 seconds.
Dec  7 15:56:07 clone-2 dhclient[4657]: DHCPREQUEST on eth12 to 192.168.56.100 port 67 (xid=0xdb610a3)
Dec  7 15:56:07 clone-2 dhclient[4657]: DHCPACK from 192.168.56.100 (xid=0xdb610a3)
Dec  7 15:56:07 clone-2 dhclient[4657]: bound to 192.168.56.101 -- renewal in 507 seconds.
Dec  7 15:56:07 clone-2 NetworkManager[1391]: <info> (eth12): DHCPv4 state changed renew -> renew
Dec  7 15:56:07 clone-2 NetworkManager[1391]: <info>   address 192.168.56.101
Dec  7 15:56:07 clone-2 NetworkManager[1391]: <info>   prefix 24 (255.255.255.0)
```


Oracle DB logs: 
$ tailf -10f alert_demo.log
```>bash-4.1$ sqlplus / as sysdba

>SQL*Plus: Release 11.2.0.1.0 Production on Wed Dec 7 15:55:15 2016

>Copyright (c) 1982, 2009, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> startup
ORA-01081: cannot start already-running ORACLE - shut it down first
SQL> exit
Disconnected from Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
bash-4.1$ tailf -10f alert_demo.log
Wed Dec 07 15:55:20 2016
Starting ORACLE instance (normal)
```

Oracle server logs:
\# tailf -10f /var/log/messages
```Dec  7 15:49:33 pghost NetworkManager[1382]: <info> (eth9): DHCPv4 state changed renew -> renew
Dec  7 15:49:33 pghost NetworkManager[1382]: <info>   address 192.168.56.103
Dec  7 15:49:33 pghost NetworkManager[1382]: <info>   prefix 24 (255.255.255.0)
Dec  7 15:49:33 pghost dhclient[1428]: bound to 192.168.56.103 -- renewal in 510 seconds.
Dec  7 15:58:03 pghost dhclient[1428]: DHCPREQUEST on eth9 to 192.168.56.100 port 67 (xid=0x10c0dd12)
Dec  7 15:58:03 pghost dhclient[1428]: DHCPACK from 192.168.56.100 (xid=0x10c0dd12)
Dec  7 15:58:03 pghost NetworkManager[1382]: <info> (eth9): DHCPv4 state changed renew -> renew
Dec  7 15:58:03 pghost NetworkManager[1382]: <info>   address 192.168.56.103
Dec  7 15:58:03 pghost NetworkManager[1382]: <info>   prefix 24 (255.255.255.0)
Dec  7 15:58:03 pghost dhclient[1428]: bound to 192.168.56.103 -- renewal in 533 seconds.
```


Please let know if need any more information.

**Comment by amitlan** [comment]
Hey Sachin, isn't there anything in the PG log related to the failing syncdb query?  What you've shown seems unrelated to the syncdb failure (although, I'm not sure that it's really unrelated).

**Comment by bwtakacy** [comment]
One more.

Could you change the log level of syncdb to `debug` ?
The log level can be changed by log4j.xml in path specified by `SYNCDB_HOME` environment variable.

**Comment by kotsachin** [comment]
@amitlan It is not related because there is nothing in PG log after I ran syncdb command .

**Comment by amitlan** [comment]
As @bwtakacy suggests, you could try to set logging parameters so that you get more details that are currently missing.

**Comment by kotsachin** [comment]
Hi @bwtakacy 

There two places where we can set log level. I set one by one. For combined log output please see attached file.

I set log level in log4j.xml as below:
log4j.xml
```
  <root>
                <level value="debug" />
                <appender-ref ref="STDOUT" />
                <appender-ref ref="FILE" />
 </root>
```

Huge messages prints on screen.
Last few lines from debug messages:
 
```
INFO  - stop JOTM
DEBUG - threadTx.set= null
DEBUG - Unexport object org.objectweb.jotm.TransactionFactoryImpl
DEBUG - UnExported objects list:
Exported Objects:
1 instances of  org.objectweb.jotm.TransactionFactoryImpl
Total number of exported objects=1
DEBUG - TransactionFactory unexported
ERROR - refresh error, see server logs for details
```

If I set below parameter to 'debug':
log4j.xml
```
     <logger name="jp.co.ntt.oss">
                <level value="debug" />
     </logger>
```

```
$ syncdb attach --master postgres --server oracle --schema syncdb --table rep_accounts
input query : SELECT aid, bid, abalance FROM "public"."pgbench_accounts"
DEBUG - input query:SELECT aid, bid, abalance FROM "public"."pgbench_accounts" 
DEBUG - oracle configuration:syncdb/jdbc:oracle:thin:@10.150.10.189:1521:demo/oracle.jdbc.driver.OracleDriver
DEBUG - postgres configuration:postgres/jdbc:postgresql://localhost:5432/master_db/org.postgresql.Driver
DEBUG - column [1] : aid
DEBUG - column [2] : bid
DEBUG - column [3] : abalance
DEBUG - column count : 3
DEBUG - refresh error, see server logs for details
ERROR - refresh error, see server logs for details
```


If I set both log levels to 'debug' as mentioned above in log4j.xml. Please find attached log file.
[syncdb.txt](https://github.com/ossc-db/syncdb/files/638675/syncdb.txt)

**Comment by amitlan** [comment]
Sachin,

In the following command:

```
$ syncdb attach --master postgres --server oracle --schema syncdb --table rep_accounts
input query : SELECT aid, bid, abalance FROM "public"."pgbench_accounts"
```

Is it intentional that you want to sync `"public"."pgbench_accounts"` with `syncdb.rep_accounts`?

By the way, I still haven't seen the error message that the actual server produced.

**Comment by kotsachin** [comment]
@amitlan 
Yes. I want to sync "public"."pgbench_accounts" from PostgreSQL database with syncdb.rep_accounts in Oracle database.

**Comment by bwtakacy** [comment]
@kotsachin 

Thanks for showing the debug logs.

These two log level are different.
The former control control the log level the libraries which syncdb used and the latter is the log level of syncdb itself.

And from the latter debug logs there are someting wrong in libraries.
Could you show the entire debug of the former one?
The lines you have already shown is the some kind of error cleanup and not the actual error messages.

**Comment by kotsachin** [comment]
@bwtakacy 

Thanks to looking in to logs.

I feel former means you are saying below:
```
<root>
                <level value="debug" />
                <appender-ref ref="STDOUT" />
                <appender-ref ref="FILE" />
 </root>
```

> Could you show the entire debug of the former one?

Attached log file has both logs so you can find there. But still I will reproduce by setting above parameter.

Please find attached log.
[syncdb.txt](https://github.com/ossc-db/syncdb/files/641324/syncdb.txt)

**Comment by bwtakacy** [comment]
Thank you for giving debug log.

But I could not found there is any explicit reason.

Hmm.

Did you check the Oracle listener log?

**Comment by kotsachin** [comment]
Please see below entries from listener log

$ vim /u01/app/oracle/product/11.2.0/dbhome_1/log/diag/tnslsnr/pghost/listener/alert/log.xml
```
<msg time='2016-12-09T12:34:30.405+05:30' org_id='oracle' comp_id='tnslsnr'
 type='UNKNOWN' level='16' host_id='pghost'
 host_addr='127.0.0.1' version='1'>
 <txt>09-DEC-2016 12:34:30 * (CONNECT_DATA=(SID=demo)(CID=(PROGRAM=JDBC Thin Client)(HOST=__jdbc__)(USER=linuxadmin))) * (ADDRESS=(PROTOCOL=tcp)(HOST=192.168.56.101)(PORT=47231)) * establish * demo * 0
 </txt>
</msg>
```

**Comment by bwtakacy** [comment]
Hmm.

So, there seems to be no connection problem.

Could you try to do some more analysis?
Does this happen with `--mode full`?
Is this happen in PG => PG case?

**Comment by kotsachin** [comment]
ok.

> Could you try to do some more analysis?
I would like to do some analysis but as this is developed in Java and I have no experience in Java, so I will be little difficult.
Still I will try to do some analysis.

Is there any recent changes to below libraries ?
What these libraries do?
The messages in log , just before 'error' message is coming from these libraries.
jotm-client.jar
jotm-core.jar 

> Does this happen with --mode full?

Yes. I tried attached command with --mode full. It is giving same error.

> Is this happen in PG => PG case?

No. PG => PG is working fine.


Thanks!!

**Comment by bwtakacy** [comment]
>Is there any recent changes to below libraries ?
What these libraries do?
The messages in log , just before 'error' message is coming from these libraries.
jotm-client.jar
jotm-core.jar

They are JTA implementation libraries which control db transactions in Java EE.
These libraries are bundled in syncdb and so they are fixed.

> >Is this happen in PG => PG case?

> No. PG => PG is working fine.

It means that there may be some configuration troubles between syncdb and Oracle, I think.
Is there some error in Oracle alert logs and trace logs?

**Comment by kfuru** [comment]
In oracle,
If there is a quotation mark, it is case sensitive.
   create table test (...)    ---> TEST (upper case)
   create table "test" (...)  --->test  (lower case)

Probably, 
try specifying parameters with uppercase letters in schema and table name in oracle.

In my environment,
$ syncdb create --master pg_mdb --schema public --table test
INFO  - create success
$ syncdb attach --master pg_mdb --server oracle --schema syncdb --table rep_test   -- NG
input query : SELECT * FROM "public"."test"
ERROR - refresh error, see server logs for details
$ syncdb attach --master pg_mdb --server oracle --schema SYNCDB --table REP_TEST   -- OK
input query : SELECT * FROM "public"."test"
INFO  - attach incremental refresh mode, subscribe id : 2
$

Wrong?

**Comment by kotsachin** [comment]
@kfuru 

Thanks for investigation and solution. 
I tried with upper case schema name and replication table. It works fine.

Can you please update same in documentation?
Is there any english document for syncdb ? If not can you please create one whenever you have free time, it is not urgent. I will try if I can.

You can close this ticket now.

Thank you again!!

**Comment by bwtakacy** [comment]
Thank you @kfuru !
This is a great work 😃

**Comment by kfuru** [comment]
Thank you for contacting me. @kotsachin
If possible, I think try to translate English when I have time.

When I translate Japanese to English ...
>When creating with the name enclosed in double quotes like "Table_A" when creating the schema and table, specify it in Table_A when syncdb option is specified.
>If you create without enclosing with double quotes, 
>specify it with TABLE_A because table_a is registered in DB in lower case in PostgreSQL and upper case in case of Oracle.

Thanks all.
