### ISSUE TITLE
create_mlog bug

### ISSUE THREAD

**Issue by nttd-ishiiaym** [ossc-db/syncdb#3]
Hi,

I found a problem on syncdb.
Could you fix the bug?

[condition]
・master is Oracle
・Oracle DB has plural same name tables on diffirent schemas.
・These tables have same name primary key constraint.

-->syncdb create 
ERROR - refresh error, see server logs for details

[test case]
create table test.table1(id int);
create table test2.table1(id int);

alter table test.table1 add constraint table1_pk primary key (id);
alter table test2.table1 add constraint table1_pk primary key (id);

sqlplus test/test@test @mlog_oracle.sql

syncdb create --master oracle --schema TEST --table TABLE1

[cause]
mlog.column_defs execute SQL which get primary key information,
but the SQL does not have JOIN key regarding schema.

[fix]
★before
SELECT c.table_name AS table_name, cc.column_name AS column_name,
c.constraint_type AS isprimary
FROM all_constraints c INNER JOIN all_cons_columns cc
ON c.table_name = cc.table_name AND c.constraint_name = cc.constraint_name
WHERE c.constraint_type = 'P' AND
c.owner = 'TEST' AND c.table_name = 'TABLE1';

★after
SELECT c.table_name AS table_name, cc.column_name AS column_name,
c.constraint_type AS isprimary
FROM all_constraints c INNER JOIN all_cons_columns cc
ON c.table_name = cc.table_name AND c.constraint_name = cc.constraint_name AND c.owner = cc.owner
WHERE c.constraint_type = 'P' AND
c.owner = 'TEST' AND c.table_name = 'TABLE1';

**Comment by nttd-ishiiaym** [comment]
I have a additional request.
syncdb emit no message when syncdb catch Exception (like SQL Exception) in debug mode.
I think it is useful  to emit Exception message in debug mode.

**Comment by kfuru** [comment]
Thank you very much.
I think that you are probably right. 

all_constraints has not been narrowed down by owner(user name)
If another user has the same table definition, it corresponds to this problem.

Note:
 PACKAGE mlog.mlog is defined by AUTHID DEFINER.
   (CREATE OR REPLACE PACKAGE mlog.mlog AUTHID DEFINER AS ...)
 When the procedure of this package is executed, it will be executed by the oracle user(dba).
 Data dictionary(all_*) is the target that the oracle user can access,
 Definition information such as tables of other users is also targeted. 

Sorry, It is difficult to handle log messages,
Regarding the error, I will fix it.

**Comment by kfuru** [comment]
Since it was easy to obtain the message at the time of exception error occurrence,
In debug mode, we added an exception error output.

Until now, since a message to become a hint was not outputted,
I think that it will be some help.

Thank you for report.

**Comment by nttd-ishiiaym** [comment]
Thank you for fixing !
